source "https://rubygems.org"

# Rails e dependências principais
gem "rails", "~> 7.2.1", ">= 7.2.1.2"
gem "puma", ">= 5.0"
gem "sprockets-rails"
gem "sqlite3", ">= 1.4"  # Remova este se usar MySQL em vez de SQLite
gem "mysql2", ">= 0.5.6" # Remova este se estiver usando SQLite

# Gems para recursos do Rails
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

# Gems de autenticação e segurança
gem "devise"
gem "devise-two-factor"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "bcrypt", "~> 3.1.7"

# Gems para ElasticSearch e Redis
gem "elasticsearch-model", "~> 7.0"
gem "elasticsearch-rails", "~> 7.0"
gem "redis", "~> 4.0"

# Gems adicionais para desenvolvimento e testes
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "rswag" # Para documentação de API com Swagger

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 5.0"  # Para testes
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end



