global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rails'
    static_configs:
      - targets: ['web:3000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
