apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: backend
          image: chat-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: 'mysql://user:password@db:3306/chat_production'
