name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t yourname/chat-backend:latest ./backend
          docker push yourname/chat-backend:latest
          docker build -t yourname/chat-frontend:latest ./frontend
          docker push yourname/chat-frontend:latest

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f ./k8s/backend-deployment.yml
          kubectl apply -f ./k8s/frontend-deployment.yml
